server:
  port: ${PORT}
spring:
  application:
    name: TaskManagement
  datasource:
    url: jdbc:mysql://localhost:3306/task_management
    username: ${USER_MYSQL}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret: secret
  expiration: 86400000